import { body } from 'express-validator';

export const postTitleValidation = body('title')
  .exists()
  .withMessage('Title is required')
  .trim()
  .notEmpty()
  .withMessage('Title cannot be empty')
  .isString()
  .withMessage('Title must be a string')
  .isLength({ max: 30 })
  .withMessage('Title must be at most 30 characters')
  .not()
  .isArray()
  .withMessage('Cannot be array')
  .not()
  .isObject()
  .withMessage('Cannot be object');

export const postShortDescriptionValidation = body('shortDescription')
  .exists()
  .withMessage('Short description is required')
  .trim()
  .notEmpty()
  .withMessage('Short description cannot be empty')
  .isString()
  .withMessage('Short description must be a string')
  .isLength({ max: 100 })
  .withMessage('Short description must be at most 100 characters')
  .not()
  .isArray()
  .withMessage('Cannot be array')
  .not()
  .isObject()
  .withMessage('Cannot be object');

export const postContentValidation = body('content')
  .exists()
  .withMessage('Content is required')
  .trim()
  .notEmpty()
  .withMessage('Content cannot be empty')
  .isString()
  .withMessage('Content must be a string')
  .isLength({ max: 1000 })
  .withMessage('Content must be at most 1000 characters')
  .not()
  .isArray()
  .withMessage('Cannot be array')
  .not()
  .isObject()
  .withMessage('Cannot be object');

export const postBlogIdValidation = body('blogId')
  .exists()
  .withMessage('Blog ID is required')
  .trim()
  .isString()
  .withMessage('Blog ID must be a string')
  .not()
  .isArray()
  .withMessage('Cannot be array')
  .not()
  .isObject()
  .withMessage('Cannot be object');
