import { body } from 'express-validator';

export const nameValidationField = body('name')
  .exists()
  .withMessage('Name is required')
  .trim()
  .notEmpty()
  .withMessage('Name is required')
  .isString()
  .withMessage('Name must be a string')
  .isLength({ max: 15 })
  .withMessage('Name must be no more than 15 characters');
export const descriptionValidationField = body('description')
  .exists()
  .withMessage('Description required')
  .isString()
  .withMessage('Must be string')
  .not()
  .isArray()
  .withMessage('Cannot be array')
  .not()
  .isObject()
  .withMessage('Cannot be object')
  .trim()
  .notEmpty()
  .withMessage('Cannot be empty')
  .isLength({ max: 500 })
  .withMessage('Description must be no more than 500 characters');
export const websiteUrlValidationField = body('websiteUrl')
  .exists()
  .trim()
  .notEmpty()
  .withMessage('Website URL is required')
  .isString()
  .withMessage('Website URL must be a string')
  .isLength({ max: 100 })
  .withMessage('Website URL must be no more than 100 characters')
  .matches(/^https:\/\/([a-zA-Z0-9_-]+\.)+[a-zA-Z0-9_-]+(\/[a-zA-Z0-9_-]+)*\/?$/)
  .withMessage('Invalid website URL format');
